-d /home/vladfe/WORK/SETUN-1958/DOCs/FPGA/PROJs/fpga_digital_ternary/impl/gwsynthesis/fpga_trits.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/vladfe/WORK/SETUN-1958/DOCs/FPGA/PROJs/fpga_digital_ternary/src/fpga_digital_ternary.cst
-cfg /home/vladfe/WORK/SETUN-1958/DOCs/FPGA/PROJs/fpga_digital_ternary/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
